repos:
-   repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.2"  # Use the sha / tag you want to point at
    hooks:
    -   id: biome-check
        additional_dependencies: ["@biomejs/biome@2.1.1"]
    -   id: biome-format
        additional_dependencies: ["@biomejs/biome@2.1.1"]
