name: Build

on:
  - push
  - pull_request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
            version: latest
            run_install: true
      - name: Run Build
        run: pnpm run build