name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  type-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: true # package manager version is in package.json
      - name: Run type-checking
        run: npm run type-check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: true # package manager version is in package.json
      - name: Run Build
        run: pnpm run build
  finish:
    name: Finish # DO NOT CHANGE THIS NAME, We have a merge checks depending on this
    runs-on: ubuntu-latest
    needs: [quality, type-safe, build]
    steps:
      - name: Run Finish
        run: echo "Finish"